# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simplify <- function(words, coeffs) {
    .Call(`_freealg_simplify`, words, coeffs)
}

free_prod <- function(words1, coeffs1, words2, coeffs2) {
    .Call(`_freealg_free_prod`, words1, coeffs1, words2, coeffs2)
}

free_sum <- function(words1, coeffs1, words2, coeffs2) {
    .Call(`_freealg_free_sum`, words1, coeffs1, words2, coeffs2)
}

free_power <- function(words, coeffs, n) {
    .Call(`_freealg_free_power`, words, coeffs, n)
}

